### PR TITLE
Fix optional features: duckdb, databricks

### PR DESCRIPTION
**Pull request by ahirner**
This excludes dataconnector features for duckdb, databricks where needed.

How to reproduce:

```
cargo build --no-default-features --features "sqlite postgres"
```

```
error[E0432]: unresolved import `data_components::duckdb`
  --> crates/runtime/src/dataconnector/duckdb.rs:18:22
   |
18 | use data_components::duckdb::DuckDBTableFactory;
   |                      ^^^^^^ could not find `duckdb` in `data_components`

error[E0432]: unresolved import `db_connection_pool::duckdbpool`
  --> crates/runtime/src/dataconnector/duckdb.rs:21:25
   |
21 | use db_connection_pool::duckdbpool::DuckDbConnectionPool;
   |                         ^^^^^^^^^^ could not find `duckdbpool` in `db_connection_pool`

error[E0433]: failed to resolve: use of undeclared crate or module `databricks`
   --> crates/runtime/src/dataconnector.rs:133:46
    |
133 |     register_connector_factory("databricks", databricks::Databricks::create).await;
    |                                              ^^^^^^^^^^ use of undeclared crate or module `databricks`
```

Errors were introduced in #1085 and #1097 and the databricks not made optional in #1029.

### CODE REVIEW

**Comment by lukekim** [comment]
Thanks! Shall we add Dremio to this PR also?

**Comment by ahirner** [comment]
> add Dremio

For consistency yes, to reduce dependencies less so. Your question revealed a problem with sqlite feature. Both fixed now.

As for CI, a `cargo check` with `--no-default-fetures` and some or all top-level features in isolation would go a long way.

**Review by sgrebnov — APPROVED** [review]

**Comment by sgrebnov** [comment]
Thank you @ahirner!
